### PR TITLE
Clarify `xticks`, `yticks` in README.md

### PR DESCRIPTION
**Pull request by Socob**
Just a tiny `README.md` change, but since there aren’t any actual ticks (i. e. little marker lines on the axes), I think it makes sense to clarify that `xticks`/`yticks` actually hide the tick **labels**.

### CODE REVIEW

**Comment by t-bltg** [comment]
Good point, thanks.

Can you modify and run `$ cd docs; julia gen_docs.jl` instead ?
`README.md` is auto-generated.

**Comment by Socob** [comment]
Oh whoops, didn’t realize that. Will do!

**Comment by t-bltg** [comment]
Oh no wait, it's `src/description.jl` that should be modified.

😅

**Comment by Socob** [comment]
@t-bltg No worries, that’s what I understood it to mean. All done now!

**Comment by t-bltg** [comment]
Awesome, thanks!

**Pull request merged**
