### PR TITLE
Improve Dates support for stairs and xlim

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by Evizero** [comment]
Nice! Thanks. Mhm I have not been active for quite a while. Do you know if anything changed concerning travis and julia since last I checked? I am a bit confused why i see no CI results here

**Comment by simonbyrne** [comment]
Not sure: it's still appearing here https://travis-ci.org/github/Evizero/UnicodePlots.jl/pull_requests

**Comment by Evizero** [comment]
Strange error. Are you by chance working on windows? I wonder if the reference files on windows might be generated differently. especially that training newline looks suspicious

**Comment by johnnychen94** [comment]
The CI is back now so can you try to rebase this PR on the new master and see if it passes the test?

**Review by t-bltg — APPROVED** [review]

**Review by johnnychen94 — APPROVED** [review]

**Pull request merged**
